import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AOSProvider from "./components/AOSProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
return (
  <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} bg-[#0f0f0f] text-white`}
    >
      <AOSProvider />

      {/* NAVBAR */}
      <header className="fixed top-0 w-full bg-black/80 backdrop-blur-md z-50 shadow-lg">
        <div className="max-w-6xl mx-auto px-6 py-4 flex justify-between items-center">
          <h1 className="text-xl font-bold tracking-wide">
            Teak Luxury
          </h1>

          <nav className="space-x-6 text-sm">
            <a href="#" className="hover:text-amber-400 transition">
              Home
            </a>
            <a href="#" className="hover:text-amber-400 transition">
              Doors
            </a>
            <a href="#" className="hover:text-amber-400 transition">
              Windows
            </a>
            <a href="#" className="hover:text-amber-400 transition">
              Contact
            </a>
          </nav>
        </div>
      </header>

      {/* PAGE CONTENT */}
      <main className="pt-24">
        {children}
      </main>

      {/* FOOTER */}
      <footer className="bg-black py-10 text-center text-gray-400 text-sm">
        © 2026 Premium Teak Wood Creations. All Rights Reserved.
      </footer>
    </body>
  </html>
);  
}
